services:
  - type: web
    name: yasodha-pg-website
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    plan: free